server:
  port: 9595
PROFILE: dev
spring:
  profiles:
    active: ${PROFILE}
  application:
    name: SECONDARY-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1.0
main:
  service:
    baseUrl: https://MAIN-SERVICE/main
auth:
  service:
    baseUrl: http://AUTH-SERVICE/auth
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 6
          max-interval: 10s
          multiplier: 1
rabbitmq:
  queue:
    name: ${RABBIT_MQ_QUEUE_NAME}
  exchange:
    name: ${RABBIT_MQ_EXCHANGE_NAME}
  routing:
    key: ${RABBIT_MQ_ROUTING_KEY}
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/secondary_service_aws
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2
rabbitmq:
  queue:
    name: epam-rabbitmq-queue-dev
  exchange:
    name: epam-rabbitmq-exchange-dev
  routing:
    key: epam-rabbitmq-routing-key-dev