server:
  port: 9595
spring:
  profiles:
    active: prod
  application:
    name: SECONDARY-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1.0
main:
  service:
    baseUrl: https://MAIN-SERVICE/main
auth:
  service:
    baseUrl: http://AUTH-SERVICE/auth
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/secondary_service_testing_module
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 6
          max-interval: 10s
          multiplier: 1
rabbitmq:
  queue:
    name: epam-rabbitmq-queue-prod
  exchange:
    name: epam-rabbitmq-exchange-prod
  routing:
    key: epam-rabbitmq-routing-key-prod
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/secondary_service_testing_module
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2
rabbitmq:
  queue:
    name: epam-rabbitmq-queue-test
  exchange:
    name: epam-rabbitmq-exchange-test
  routing:
    key: epam-rabbitmq-routing-key-test