spring:
  application:
    name: AUTH-SERVICE
  profiles:
    active: dev
server:
  port: 7575
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: testing_module
  datasource:
    url: jdbc:postgresql://localhost:5432/epam_tasks
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: testing_module
jwt:
  access:
    token:
      expiry: 150000000
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: testing_module_prod
  datasource:
    url: jdbc:postgresql://localhost:5432/epam_tasks
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: testing_module_prod
jwt:
  access:
    token:
      expiry: 150000000
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58

